// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform: $defaultTargetPlatform',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3PELui0nSAeSsMdvR2ud2CTqW7AjU7Yg',
    appId: '1:106648713758:web:8a4ed52e13aabdf6510c0f',
    messagingSenderId: '106648713758',
    projectId: 'niflex-79a03',
    authDomain: 'niflex-79a03.firebaseapp.com',
    storageBucket: 'niflex-79a03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwUZM3N9pbGfA7DxrHTDZL1u038tTeu2E',
    appId: '1:106648713758:android:6b810dd19a040843510c0f',
    messagingSenderId: '106648713758',
    projectId: 'niflex-79a03',
    storageBucket: 'niflex-79a03.appspot.com',
    androidClientId:
        '106648713758-vcrf17j54mlqrd8j4k6r762iun9418er.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSxSJDnw5IaZGb17-qO-nHs0oKsAtydY',
    appId: '1:879683392852:ios:06ea0b0032b9383b5324c1',
    messagingSenderId: '879683392852',
    projectId: 'quickstart-flutter',
    storageBucket: 'quickstart-flutter.appspot.com',
    iosClientId:
        '879683392852-033rm5j7vc5spd6frsolbs4g8jqfd7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiSxSJDnw5IaZGb17-qO-nHs0oKsAtydY',
    appId: '1:879683392852:ios:06ea0b0032b9383b5324c1',
    messagingSenderId: '879683392852',
    projectId: 'quickstart-flutter',
    storageBucket: 'quickstart-flutter.appspot.com',
    iosClientId:
        '879683392852-033rm5j7vc5spd6frsolbs4g8jqfd7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
